name: Trigger auto deployment for cfgdhfygn

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/cfgdhfygn-AutoDeployTrigger-099e7475-5571-44b9-a7ca-8b97325ea0ad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CFGDHFYGN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CFGDHFYGN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CFGDHFYGN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: linuxenv.azurecr.io
          registryUsername: ${{ secrets.CFGDHFYGN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CFGDHFYGN_REGISTRY_PASSWORD }}
          containerAppName: cfgdhfygn
          resourceGroup: TaiwoRG
          imageToBuild: linuxenv.azurecr.io/cfgdhfygn:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


